language: rust
sudo: false
cache:
  - apt
  - cargo

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env:
        - TARGET=x86_64-apple-darwin
        - DEPLOY_RELEASE=1

install: .travis/install.sh
script:
  - cargo build --all
  - cargo test --all

before_deploy:
  - .travis/before_deploy.sh

deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
    body: "Automatically deployed release"
    on:
      condition: $DEPLOY_RELEASE = 1
      tags: true
    api_key: $GH_TOKEN

env:
  global:
    - PROJECT_NAME: "hpk"
    - secure: "J44BBeGuzJMbEhSyea1UNFGQ43EcI7/kbvWKwgzLBsmZkZed/YKrwp4HHUGr+gDOQe+cpgGnVeYywdrhbk7wmE4mX+HQWntn2/OJrSbZHamSmMsH2hFH3l3k7OthFl2TpPXm+Bo1bSiqhbKXenz3/EMX23+TA32Rw5OPdgOev6AMBUAg3Ujw0RjY1nCsziQ9CDBoThe3jd/izApeRii7TRb8yFwGoRdlS3EPA62FRik7y7jpqmr+q3o/vQk/VKEJ8QexgRLDqmI3hf89c+GLGHskrMSLxz5cFIaR1XB+CKu+FDoc03GLgTq9aaPEqrg3mfp6m4RNsuI1Xle6BNzFLqNyDrZiMRz+k5OxhlyTot6sHYSxzTx1o3vFhgL3TeSOluU//XDDyLrc0+Pc1ivoi+aqqlWGec57Y3tErEz/sUzjCXcDeEbz4b7Nn31SjOnQjRYYZNOMpDxjfJb5TzYIBowkaE8NA3gDYUfZ/5/guKfWOwtrgRNu1YIX1HK+lXTfYmTVaDdyE3JOQLdmtSuY+rqGdL4PYjXB7IfJKtDV221W6xHpj4PHG/fFWeY782AXM6taC3hajjHkIMaltLmhDfGgYBPY3z6FXPI1nAfyEuMvSdhdiMSkOutx38pfAwU6h70UI8hwxIA6J8VUT2lyEnjJ036o8P2sq7jaw6jCj6s="

notifications:
  email:
    on_success: never
