[package]
name = "hpk"
version = "0.1.0"
description = "HPK archiver for Haemimont Engine game files (Tropico 3-5, Omerta, Victor Vran etc.)"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]

[features]
lz4frame = ["lz4"]

[lib]
name = "hpk"
path = "src/hpk/mod.rs"

[[bin]]
name = "hpk"
path = "src/main.rs"

[[bin]]
name = "hpk-gtk"
path = "src/bin/gtk.rs"

[dependencies]
byteorder = "1"
gio="0.3"
flate2 = "1"
lz4-compress="0"
walkdir="2"
tempdir="0.3"

[dependencies.clap]
default-features = false
version = "^2"

[dependencies.lz4]
version="1"
optional=true

[dependencies.gtk]
features=["v3_22"]
version="0.3"

[profile.release]
lto=true
