[package]
name = "hpk"
version = "0.1.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]

[dependencies]
byteorder = "1.1"
flate2 = "0.2"
tempdir = "0.3"
walkdir="2"

[dependencies.clap]
default-features = false
version = "^2"

[profile.release]
lto=true
