[package]
name = "hpk"
version = "0.1.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]

[dependencies]
byteorder = "1.1"
libflate = "0.1"
tempdir = "0.3"

[dependencies.clap]
default-features = false
version = "^2"
