[package]
name = "hpk"
version = "0.1.0"
description = "HPK archiver for Haemimont Engine game files (Tropico 3-5, Omerta, Victor Vran etc.)"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]

[lib]
name = "hpk"
path = "src/hpk/mod.rs"

[[bin]]
name = "hpk"
path = "src/main.rs"

[dependencies]
byteorder = "1"
flate2 = "1"
lz4="1"
lz4-compress="0"
walkdir="2"

[dependencies.clap]
default-features = false
version = "^2"

[profile.release]
lto=true
